### PR TITLE
Add check that collision-ode component is installed

### PR DESCRIPTION
**Pull request by traversaro**
As this component is required by ignition-physics.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Blocked by https://github.com/conda-forge/libode-feedstock/pull/5 .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Looks like this is ready to be merged? Only ppc failing ..

**Comment by traversaro** [comment]
I restarted the build and Travis seems happy.

**Comment by Tobias-Fischer** [comment]
Great - do you or @wolfv wanna click merge?

**Pull request merged**
