### PR TITLE
Depend on bullet-cpp and check that bullet collision detector is built and fix linking of fcl and assimp on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Now the pure C++ bullet library is contained in the bullet-cpp package (see https://github.com/conda-forge/bullet-feedstock/pull/28). Furthermore, as in some downstream projects I will require the buller collision detector (see https://github.com/ignitionrobotics/ign-physics/pull/225 and https://github.com/ignitionrobotics/ign-physics/pull/239) better to apply Beyonce' Rule and add a test for it. 

Also, fix link with fcl and assimp by backporting https://github.com/dartsim/dart/pull/1510 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Phew, looks like the bullet-cpp build does the job? :)

**Comment by traversaro** [comment]
> 
> 
> Phew, looks like the bullet-cpp build does the job? :)

It seems so!

**Comment by traversaro** [comment]
Travis build blocked by https://github.com/conda-forge/bullet-feedstock/pull/30 .

**Comment by traversaro** [comment]
> 
> 
> Travis build blocked by [conda-forge/bullet-feedstock#30](https://github.com/conda-forge/bullet-feedstock/pull/30) .

Fixing ppc64le on bullet probably may take some more time, so let's merge and we will fix the ppc64le builds later.

**Comment by wolfv** [comment]
sounds good!

**Pull request merged**
