### PR TITLE
Add Windows compilation

### PR DESCRIPTION
**Pull request by traversaro**
Add Windows support by backporting the https://github.com/dartsim/dart/pull/1541 to 6.9 releases.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Backport of https://github.com/dartsim/dart/pull/1541 and https://github.com/dartsim/dart/pull/1542 worked fine, PR is ready for review to be merged. fyi @wolfv @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
LGTM, thanks!

**Comment by wolfv** [comment]
the only comment I have is that this builds a static lib on Windows, but I think that's fine (especially if it would be difficult to turn on dll compilation).

**Comment by wolfv** [comment]
awesome stuff, btw!

**Comment by traversaro** [comment]
> 
> 
> the only comment I have is that this builds a static lib on Windows, but I think that's fine (especially if it would be difficult to turn on dll compilation).

Yes, upstream issue: https://github.com/dartsim/dart/issues/1501 .

**Comment by wolfv** [comment]
Alright. very cool, the robotics ecosystem on conda-forge is really growing a lot.

**Pull request merged**
